# Generated by Django 5.1.3 on 2024-12-06 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryID', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=255, unique=True)),
                ('categoryOwner', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('userPassword', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskID', models.AutoField(primary_key=True, serialize=False)),
                ('taskName', models.CharField(max_length=255, unique=True)),
                ('taskDescription', models.TextField()),
                ('taskCreationDate', models.DateField(auto_now_add=True)),
                ('taskStatus', models.IntegerField(default=0)),
                ('taskCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category', to_field='categoryName')),
            ],
        ),
    ]
