# Generated by Django 5.1.3 on 2024-12-09 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_task_taskcategory_delete_user_task_taskowner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskScheduledFor',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
